export interface GameConfig {
  id: string;
  name: string;
  emoji: string;
  description: string;
  minPlayers: number;
  maxPlayers: number;
  category: 'poker' | 'strategy' | 'luck' | 'casual' | 'solo';
  rules: {
    objective: string;
    howToPlay: string[];
    scoring: string;
    tips: string[];
  };
}

export const GAMES: GameConfig[] = [
  {
    id: 'texas-holdem',
    name: "Texas Hold'em",
    emoji: '🃏',
    description: 'The world\'s most popular poker variant. Make the best 5-card hand using 2 hole cards and 5 community cards.',
    minPlayers: 2,
    maxPlayers: 6,
    category: 'poker',
    rules: {
      objective: 'Win chips by making the best 5-card poker hand or by forcing all other players to fold.',
      howToPlay: [
        'Each player is dealt 2 private hole cards face down.',
        'A round of betting occurs (Pre-Flop). Players can fold, call, or raise.',
        'Three community cards are dealt face up (The Flop). Another betting round occurs.',
        'A fourth community card is dealt (The Turn). Another betting round occurs.',
        'A fifth community card is dealt (The River). A final betting round occurs.',
        'Remaining players reveal their hands (Showdown). Best 5-card hand wins the pot.',
        'Hand rankings from highest: Royal Flush, Straight Flush, Four of a Kind, Full House, Flush, Straight, Three of a Kind, Two Pair, Pair, High Card.',
      ],
      scoring: 'Players win the pot (all bets collected). Chip leader after all rounds wins the game.',
      tips: [
        'Position matters — acting last gives you more information.',
        'Don\'t play every hand. Be selective with your starting cards.',
        'Pay attention to the community cards and what hands they make possible.',
        'Watch your opponents\' betting patterns for tells.',
      ],
    },
  },
  {
    id: 'five-card-draw',
    name: 'Five Card Draw',
    emoji: '🎴',
    description: 'Classic draw poker. Get dealt 5 cards, trade in unwanted cards, and make the best hand.',
    minPlayers: 2,
    maxPlayers: 5,
    category: 'poker',
    rules: {
      objective: 'Have the best 5-card poker hand at showdown, or be the last player standing.',
      howToPlay: [
        'Each player is dealt 5 cards face down.',
        'First betting round: players can fold, call the big blind, or raise.',
        'Draw phase: each player may discard 0–5 cards and receive new ones.',
        'Second betting round: remaining players bet again.',
        'Showdown: remaining players reveal hands. Best hand wins the pot.',
        'Standard poker hand rankings apply (Royal Flush down to High Card).',
      ],
      scoring: 'Winner takes the entire pot. In a session, the player with the most chips wins.',
      tips: [
        'Draw fewer cards to bluff stronger hands.',
        'Keep pairs and higher — don\'t chase straights or flushes with weak starts.',
        'If you have two pair or better, consider standing pat (drawing 0 cards).',
      ],
    },
  },
  {
    id: 'rummy',
    name: 'Rummy',
    emoji: '🀄',
    description: 'Form sets and runs with your cards before anyone else. The classic matching card game.',
    minPlayers: 2,
    maxPlayers: 6,
    category: 'strategy',
    rules: {
      objective: 'Be the first player to get rid of all cards by forming melds (sets and runs).',
      howToPlay: [
        'Each player is dealt 10 cards (2 players) or 7 cards (3+ players).',
        'On your turn: draw one card from the draw pile or discard pile.',
        'Form melds: Sets (3-4 cards of same rank) or Runs (3+ cards same suit in sequence).',
        'Lay down melds to the table when ready.',
        'You may also add cards to existing melds on the table (laying off).',
        'End your turn by discarding one card to the discard pile.',
        'Win by emptying your hand completely.',
      ],
      scoring: 'The winner scores points equal to the unmelded cards remaining in opponents\' hands. Face cards = 10pts, Ace = 1pt, others = face value.',
      tips: [
        'Draw from the discard pile only if it helps your hand immediately.',
        'Watch what opponents pick up — it tells you what they need.',
        'Hold onto wild cards (jokers) for flexible use.',
        'Try to keep track of which cards have been discarded.',
      ],
    },
  },
  {
    id: 'gin-rummy',
    name: 'Gin Rummy',
    emoji: '🍸',
    description: 'Two-player rummy with knocking and gin. Minimize your deadwood to score points.',
    minPlayers: 2,
    maxPlayers: 2,
    category: 'strategy',
    rules: {
      objective: 'Reduce deadwood (unmelded cards) to score. Knock when deadwood is 10 or less; go Gin for bonus.',
      howToPlay: [
        'Each player is dealt 10 cards.',
        'Non-dealer draws from the upcard or stock on their turn.',
        'Form melds: Sets (same rank) and Runs (same suit, sequential).',
        'Knock when your deadwood total is 10 or less. Discard face-down to signal.',
        'Both players reveal melds. Opponent may lay off cards on your melds.',
        'If knocker\'s deadwood is less, they score the difference.',
        'Gin: knock with 0 deadwood for a 25-point bonus.',
        'Undercut: if opponent\'s deadwood ≤ knocker\'s, opponent gets 25-point bonus.',
      ],
      scoring: 'First to 100 points wins. Score difference in deadwood each hand. Bonuses: Gin +25, Undercut +25, Game bonus +100.',
      tips: [
        'Aim for Gin when opponent seems far from knocking.',
        'Knock early with low deadwood to avoid being undercut.',
        'Watch the discard pile to predict opponent\'s melds.',
      ],
    },
  },
  {
    id: 'uno',
    name: 'UNO',
    emoji: '🟥',
    description: 'The iconic color-matching card game. Match color or number, play action cards, and shout UNO!',
    minPlayers: 2,
    maxPlayers: 6,
    category: 'casual',
    rules: {
      objective: 'Be the first player to empty your hand. Call "UNO!" when you have one card left.',
      howToPlay: [
        'Each player is dealt 7 cards. Flip top card to start the discard pile.',
        'Match the top card by color, number, or symbol.',
        'Special cards: Skip (next player loses turn), Reverse (direction changes), Draw Two (next draws 2).',
        'Wild: choose any color. Wild Draw Four: choose color AND next player draws 4.',
        'If you cannot play, draw one card. If playable, play it; otherwise keep it.',
        'Shout "UNO!" when you have exactly 1 card left or draw 2 cards as penalty.',
        'First to empty hand wins the round.',
      ],
      scoring: 'Winner scores points from opponents\' remaining cards: numbered cards = face value, action cards = 20pts, wild cards = 50pts. First to 500 wins.',
      tips: [
        'Save Wild Draw Four for critical moments.',
        'Stack action cards strategically.',
        'Don\'t forget to say UNO — opponents can challenge you!',
        'Change color to one you have many of.',
      ],
    },
  },
  {
    id: 'blackjack',
    name: 'Blackjack',
    emoji: '🃏',
    description: 'Beat the dealer by getting as close to 21 as possible without going over.',
    minPlayers: 1,
    maxPlayers: 5,
    category: 'luck',
    rules: {
      objective: 'Beat the dealer by having a hand closer to 21 without exceeding it (busting).',
      howToPlay: [
        'Place your bet before cards are dealt.',
        'You and the dealer each receive 2 cards. One dealer card is face down.',
        'Card values: numbered cards = face value, face cards (J/Q/K) = 10, Ace = 1 or 11.',
        'Hit: take another card. Stand: keep your current hand.',
        'Double Down: double your bet and take exactly one more card.',
        'Split: if dealt two of the same rank, split into two separate hands.',
        'Dealer reveals hidden card and must hit until reaching 17 or higher.',
        'If dealer busts, all standing players win. Otherwise closest to 21 wins.',
        'Blackjack (Ace + 10-value on initial deal) pays 3:2.',
      ],
      scoring: 'Win = 1:1 payout. Blackjack = 3:2 payout. Push (tie) = bet returned. Bust = lose bet.',
      tips: [
        'Always stand on 17 or higher.',
        'Double down on 11 against dealer\'s 2-10.',
        'Never split 10s or 5s. Always split Aces and 8s.',
        'Assume the dealer\'s hidden card is a 10.',
      ],
    },
  },
  {
    id: 'war',
    name: 'War',
    emoji: '⚔️',
    description: 'The ultimate battle of the cards. Flip, compare, and capture to collect the whole deck.',
    minPlayers: 2,
    maxPlayers: 2,
    category: 'luck',
    rules: {
      objective: 'Collect all 52 cards by winning battles against your opponent.',
      howToPlay: [
        'The deck is split equally between both players (26 cards each), face down.',
        'Each player simultaneously flips their top card to the center.',
        'The higher card wins both cards (added to winner\'s bottom of pile).',
        'Card ranking: Ace high, then K, Q, J, 10... 2 lowest.',
        'Tie = WAR! Each player places 3 cards face-down, then flips a battle card.',
        'Winner of the war takes all cards in the center.',
        'If war causes a player to run out of cards, they lose.',
        'Game ends when one player has all 52 cards.',
      ],
      scoring: 'Winner is the player who collects all cards. No points — just victory!',
      tips: [
        'War is pure luck — no strategy involved!',
        'Watch for long war chains that can flip the game.',
        'Enjoy the tension of the simultaneous reveals.',
      ],
    },
  },
  {
    id: 'solitaire',
    name: 'Solitaire',
    emoji: '🂡',
    description: 'Classic Klondike Solitaire. Sort all cards to the foundation piles by suit.',
    minPlayers: 1,
    maxPlayers: 1,
    category: 'solo',
    rules: {
      objective: 'Move all 52 cards to the four foundation piles, sorted by suit from Ace to King.',
      howToPlay: [
        'Set up: 7 tableau columns (1-7 cards), only top card face up. 24 cards in the stock pile.',
        'Foundation piles start with Aces and build up by suit (A, 2, 3... K).',
        'Tableau: build columns in descending order, alternating red/black suits.',
        'Draw from the stock pile (1 or 3 cards at a time).',
        'Move face-up tableau cards (and stacks) to build sequences.',
        'Flip face-down cards by moving the cards above them.',
        'Empty tableau columns can only be filled with Kings.',
        'Win when all cards are on the foundation piles.',
      ],
      scoring: 'Complete the game as fast as possible. Score based on moves made and time taken.',
      tips: [
        'Expose face-down cards as quickly as possible.',
        'Don\'t move cards to foundations too early if you need them for tableau.',
        'Prioritize longer tableau columns first.',
        'An empty column is a powerful resource — use it wisely.',
      ],
    },
  },
  {
    id: 'hearts',
    name: 'Hearts',
    emoji: '♥️',
    description: 'Avoid taking hearts and the Queen of Spades. Shoot the moon to flip the script!',
    minPlayers: 4,
    maxPlayers: 4,
    category: 'strategy',
    rules: {
      objective: 'Have the lowest score when any player reaches 100 points. Avoid hearts and the Queen of Spades.',
      howToPlay: [
        'Deal all 52 cards evenly (13 per player).',
        'Passing: before each round, pass 3 cards left (1st), right (2nd), across (3rd), keep (4th).',
        'Player with 2♣ leads the first trick.',
        'Must follow suit if possible. If not, play any card.',
        'Highest card of the led suit wins the trick.',
        'Hearts cannot be led until they\'ve been "broken" (played on a trick).',
        'Shooting the Moon: take ALL hearts and Q♠ — all opponents get 26 points instead.',
        'Play continues until someone reaches 100 points.',
      ],
      scoring: 'Each heart = 1 point, Q♠ = 13 points. Shoot the Moon: opponents get 26 pts or you subtract 26. Lowest score wins.',
      tips: [
        'Pass high cards in dangerous suits to the left.',
        'If you get the Ace or King of Spades, consider going for the moon.',
        'Watch the passing direction each round.',
        'Track which hearts have been played to know when to safely lead them.',
      ],
    },
  },
  {
    id: 'spades',
    name: 'Spades',
    emoji: '♠️',
    description: 'Team up, bid your tricks, and take at least what you promised. Spades are always trump!',
    minPlayers: 4,
    maxPlayers: 4,
    category: 'strategy',
    rules: {
      objective: 'As a team, bid the exact number of tricks you\'ll take and reach 500 points first.',
      howToPlay: [
        'Players sit as two teams: North/South vs East/West.',
        'Deal all 52 cards (13 per player).',
        'Bidding: each player bids how many tricks they expect to win. Nil bid = 0 tricks.',
        'Spades are always trump — they beat all other suits.',
        'Player left of dealer leads first. Must follow suit; if can\'t, play any card.',
        'Highest trump wins; otherwise highest card of led suit wins.',
        'Teams must take at least their combined bid to score.',
        'Overtricks (bags) count +1 but accumulate — 10 bags = -100 penalty.',
      ],
      scoring: 'Make bid: 10 × bid + overtricks. Fail bid: -10 × bid. Nil bid made: +100. Nil failed: -100. First team to 500 wins.',
      tips: [
        'Communicate through your bids — don\'t over-bid.',
        'Lead your partner\'s bid suit to help them establish tricks.',
        'Save high spades for when it counts.',
        'Watch bag accumulation — 10 bags costs you dearly.',
      ],
    },
  },
  {
    id: 'go-fish',
    name: 'Go Fish',
    emoji: '🐟',
    description: 'Ask opponents for cards to complete your books of four. The classic family favorite!',
    minPlayers: 2,
    maxPlayers: 6,
    category: 'casual',
    rules: {
      objective: 'Collect the most "books" (sets of all 4 cards of one rank) by the end of the game.',
      howToPlay: [
        'Deal 7 cards each (2-3 players) or 5 cards each (4+ players). Remaining cards form the pond.',
        'On your turn, ask any opponent for a specific rank you already hold in your hand.',
        'If the opponent has any cards of that rank, they must give them all to you. Take another turn.',
        'If they don\'t have any, they say "Go Fish!" and you draw from the pond.',
        'If you draw the card you asked for, show it and take another turn.',
        'When you have all 4 cards of a rank, lay them down as a book.',
        'When a player runs out of cards, they draw 5 new ones from the pond.',
        'Game ends when the pond is empty and no one can play. Most books wins.',
      ],
      scoring: 'Count the number of books (sets of 4) each player has collected. Most books wins!',
      tips: [
        'Remember what other players have asked for — it reveals their hand.',
        'Ask players who have drawn many cards — they may have what you need.',
        'Complete books as quickly as possible to reduce your hand size.',
      ],
    },
  },
  {
    id: 'crazy-eights',
    name: 'Crazy Eights',
    emoji: '8️⃣',
    description: 'Match suit or number, play special 8s to change the suit, and empty your hand first!',
    minPlayers: 2,
    maxPlayers: 5,
    category: 'casual',
    rules: {
      objective: 'Be the first player to get rid of all your cards.',
      howToPlay: [
        'Deal 8 cards to each player (5 cards with 3+ players). Flip top card to start discard pile.',
        'On your turn, play a card matching the top discard by suit or rank.',
        'Eights are wild — play on anything and declare the new suit.',
        'If you can\'t play, draw cards until you can or the deck runs out.',
        'Special rules (optional): 2 = next player draws 2, Q = skip next player, A = reverse.',
        'First player to empty their hand wins the round.',
      ],
      scoring: 'Winner scores points from opponents\' remaining cards: Eights = 50pts, face cards = 10pts, Aces = 1pt, others = face value. First to 200 wins.',
      tips: [
        'Save your 8s for when you\'re stuck or to change suit strategically.',
        'Pay attention to what suit is declared after an 8 is played.',
        'Try to keep cards in multiple suits so you\'re rarely stuck.',
      ],
    },
  },
  {
    id: 'old-maid',
    name: 'Old Maid',
    emoji: '👵',
    description: 'Draw cards from opponents to make pairs. Don\'t get stuck with the Old Maid!',
    minPlayers: 2,
    maxPlayers: 6,
    category: 'casual',
    rules: {
      objective: 'Get rid of all your cards by making pairs. Avoid being left with the "Old Maid" (the unmatched Queen).',
      howToPlay: [
        'Remove three Queens from the deck, leaving one (the Old Maid).',
        'Deal all cards to players (uneven is fine).',
        'All players immediately discard any pairs from their hand face down.',
        'The player to dealer\'s left fans their cards face-down.',
        'The next player draws one card blindly. If it makes a pair, discard it.',
        'Continue clockwise — each player draws one card from the player to their left.',
        'As pairs are completed, players run out of cards and are safe.',
        'The player stuck with the lone Queen (Old Maid) loses!',
      ],
      scoring: 'The player left holding the Old Maid loses the round. Play multiple rounds and track losses — fewest losses wins.',
      tips: [
        'Try to subtly make the Old Maid slightly more prominent without being caught.',
        'Watch the reactions of players when they draw cards.',
        'Getting down to few cards fast is always good.',
      ],
    },
  },
  {
    id: 'snap',
    name: 'Snap',
    emoji: '👋',
    description: 'Flip cards and be the FIRST to shout SNAP when two match. Speed and reflexes win!',
    minPlayers: 2,
    maxPlayers: 6,
    category: 'luck',
    rules: {
      objective: 'Collect all the cards by being the quickest to call "SNAP!" when matching cards appear.',
      howToPlay: [
        'Deal all cards face-down evenly among players.',
        'Players take turns flipping their top card to their own face-up pile.',
        'When the top cards of any two players\' piles match in rank, shout "SNAP!"',
        'First player to call "SNAP!" takes both matching piles, adding them to the bottom of their pile.',
        'If you call "SNAP!" incorrectly, you give one card to each other player.',
        'A player who runs out of cards is out of the game.',
        'Last player with cards wins.',
        'Central Snap variant: all cards go to a central pile — snap it to win everything.',
      ],
      scoring: 'Last player standing with cards wins. For a quick game, set a time limit and the player with most cards wins.',
      tips: [
        'Stay focused — matches can happen unexpectedly.',
        'Keep your eye on multiple piles at once.',
        'Don\'t false snap — the penalty adds up.',
        'Speed is everything — hesitation costs you.',
      ],
    },
  },
];

export function getGame(id: string): GameConfig | undefined {
  return GAMES.find((g) => g.id === id);
}
